/** The testIDs of the MyAgent screen: the contract the e2e drivers and the tests hold against. Values never change meaning; add, never rename. */
export const MyAgentIds = {
  vettingRow: 'MyAgentVettingRow',
  vettingSeat: 'MyAgentVettingSeat',
  vettingOpen: 'MyAgentVettingOpen',
  identityCard: 'MyAgentIdentityCard',
  personaDid: 'MyAgentPersonaDid',
  openCommunity: 'MyAgentOpenCommunity',
  createIdentityButton: 'CreateIdentityButton',
  awaitingConsent: 'MyAgentAwaitingConsent',
  noApprovals: 'MyAgentNoApprovals',
  approvalCard: 'MyAgentApprovalCard',
  approveConsentButton: 'ApproveConsentButton',
  denyConsentButton: 'DenyConsentButton',
  approvalDecided: 'MyAgentApprovalDecided',
  noInvitations: 'MyAgentNoInvitations',
  invitationCard: 'MyAgentInvitationCard',
  joinCommunityButton: 'JoinCommunityButton',
  membershipCard: 'MyAgentMembershipCard',
  membershipRole: 'MyAgentMembershipRole',
  communityRow: 'MyAgentCommunityRow',
  activity: 'MyAgentActivity',
  connecting: 'MyAgentConnecting',
  openYourAgentButton: 'OpenYourAgentButton',
  card: 'MyAgentCard',
  host: 'MyAgentHost',
  managerDid: 'MyAgentManagerDid',
  did: 'MyAgentDid',
  peerLeg: 'MyAgentPeerLeg',
  connectCommunityButton: 'ConnectCommunityButton',
  linkCard: 'MyAgentLinkCard',
  continueLink: 'MyAgentContinueLink',
  linkYourAgentButton: 'LinkYourAgentButton',
  linkByAddressButton: 'LinkByAddressButton',
  linkOtherPhoneHint: 'LinkOtherPhoneHint',
  enrolCard: 'MyAgentEnrolCard',
  connectMyAgentButton: 'ConnectMyAgentButton',
  devices: 'AgentDevices',
  error: 'MyAgentError',
  holdingError: 'MyAgentHoldingError',
} as const
export type MyAgentId = (typeof MyAgentIds)[keyof typeof MyAgentIds]
