/** The testIDs of the VtaAgentHome screen: the contract the e2e drivers and the tests hold against. Values never change meaning; add, never rename. */
export const VtaAgentHomeIds = {
  homeLeaving: 'AgentHomeLeaving',
  homeLink: 'AgentHomeLink',
  intro: 'AgentIntro',
  introButtons: 'AgentIntroButtons',
  introNext: 'AgentIntroNext',
  introSkip: 'AgentIntroSkip',
  doors: 'AgentDoors',
  invited: 'AgentInvited',
  invitationWaiting: 'AgentInvitationWaiting',
  joinCommunity: 'AgentJoinCommunity',
  home: 'AgentHome',
  homeTitle: 'AgentHomeTitle',
  catchingUp: 'AgentCatchingUp',
  gone: 'AgentGone',
  goneWhy: 'AgentGoneWhy',
  goneLinkNew: 'AgentGoneLinkNew',
  goneTryAgain: 'AgentGoneTryAgain',
  gaveUp: 'AgentGaveUp',
  tryAgain: 'AgentTryAgain',
  seat: 'AgentSeat',
  journeyJoined: 'AgentJourneyJoined',
  journey: 'AgentJourney',
  journeyRow: 'AgentJourneyRow',
  whatIsMyAgent: 'WhatIsMyAgent',
  addedCard: 'AgentAddedCard',
  addedUse: 'AgentAddedUse',
  addedKeep: 'AgentAddedKeep',
  vetterCard: 'AgentVetterCard',
  openDesk: 'AgentOpenDesk',
  vetterLapsed: 'AgentVetterLapsed',
  nextStep: 'AgentNextStep',
  nextStepText: 'AgentNextStepText',
  nextInvitation: 'AgentNextInvitation',
  continueVetting: 'AgentContinueVetting',
  holds: 'AgentHolds',
  communityHighlighted: 'AgentCommunityHighlighted',
  holdsStale: 'AgentHoldsStale',
  joinAnother: 'AgentJoinAnother',
} as const
export type VtaAgentHomeId = (typeof VtaAgentHomeIds)[keyof typeof VtaAgentHomeIds]
