/** The testIDs of the VtaCreateAgent screen: the contract the e2e drivers and the tests hold against. Values never change meaning; add, never rename. */
export const VtaCreateAgentIds = {
  createIntro: 'AgentCreateIntro',
  createOpenHost: 'AgentCreateOpenHost',
  createContinue: 'AgentCreateContinue',
  createAddress: 'AgentCreateAddress',
  createAddressInput: 'AgentCreateAddressInput',
  createSwitchToExisting: 'AgentCreateSwitchToExisting',
  createScanAddress: 'AgentCreateScanAddress',
  createPasteAddress: 'AgentCreatePasteAddress',
  createAddressContinue: 'AgentCreateAddressContinue',
  createOwnerCode: 'AgentCreateOwnerCode',
  createAsDevice: 'AgentCreateAsDevice',
  createOwnerBody: 'AgentCreateOwnerBody',
  createOwnerHowToggle: 'AgentCreateOwnerHowToggle',
  createOwnerHow: 'AgentCreateOwnerHow',
  createCopyCode: 'AgentCreateCopyCode',
  createShareCode: 'AgentCreateShareCode',
  createShowCode: 'AgentCreateShowCode',
  createOwnerDid: 'AgentCreateOwnerDid',
  createWaiting: 'AgentCreateWaiting',
  createError: 'AgentCreateError',
  createCheckAgain: 'AgentCreateCheckAgain',
  createConnect: 'AgentCreateConnect',
  createProgress: 'AgentCreateProgress',
  backupAddressQr: 'AgentBackupAddressQr',
  backupScanThisHeading: 'AgentBackupScanThisHeading',
  backupAddressQrCode: 'AgentBackupAddressQrCode',
  backupShowAsText: 'AgentBackupShowAsText',
  backupAddressText: 'AgentBackupAddressText',
  backupCopyAddress: 'AgentBackupCopyAddress',
  backupShareAddress: 'AgentBackupShareAddress',
  backupOtherKinds: 'AgentBackupOtherKinds',
  backupNext: 'AgentBackupNext',
  backupEnterCode: 'AgentBackupEnterCode',
  backupScanCode: 'AgentBackupScanCode',
  backupCodeInput: 'AgentBackupCodeInput',
  backupScanButton: 'AgentBackupScanButton',
  backupPasteCode: 'AgentBackupPasteCode',
  backupAdd: 'AgentBackupAdd',
  createReady: 'AgentCreateReady',
  backupAdded: 'AgentBackupAdded',
  backupNone: 'AgentBackupNone',
  createJoin: 'AgentCreateJoin',
  createDone: 'AgentCreateDone',
  createScroll: 'AgentCreateScroll',
} as const
export type VtaCreateAgentId = (typeof VtaCreateAgentIds)[keyof typeof VtaCreateAgentIds]
