/** The testIDs of the VtaLink screen: the contract the e2e drivers and the tests hold against. Values never change meaning; add, never rename. */
export const VtaLinkIds = {
  confirm: 'VtaLinkConfirm',
  hostSite: 'VtaLinkHostSite',
  agentAddress: 'VtaLinkAgentAddress',
  button: 'VtaLinkButton',
  cancel: 'VtaLinkCancel',
  host: 'VtaLinkHost',
  hostSettingUp: 'VtaLinkHostSettingUp',
  state: 'VtaLinkState',
  code: 'VtaLinkCode',
  forOtherPhone: 'VtaLinkForOtherPhone',
  keyQr: 'VtaLinkKeyQr',
  showAsText: 'VtaLinkShowAsText',
  manualDid: 'VtaLinkManualDid',
  noAnswer: 'VtaLinkNoAnswer',
  waitingForPhone: 'VtaLinkWaitingForPhone',
  checkAgain: 'VtaLinkCheckAgain',
  copyKey: 'VtaLinkCopyKey',
  shareKey: 'VtaLinkShareKey',
  showingKey: 'VtaLinkShowingKey',
  resumed: 'VtaLinkResumed',
  shareKeyHint: 'VtaLinkShareKeyHint',
  giveKeyHow: 'VtaLinkGiveKeyHow',
  showTheCode: 'VtaLinkShowTheCode',
  notYet: 'VtaLinkNotYet',
  checkGrant: 'VtaLinkCheckGrant',
  done: 'VtaLinkDone',
  linkedBody: 'VtaLinkLinkedBody',
  continue: 'VtaLinkContinue',
  error: 'VtaLinkError',
  communityAgentCleanup: 'VtaLinkCommunityAgentCleanup',
  errorDetailsToggle: 'VtaLinkErrorDetailsToggle',
  errorDetail: 'VtaLinkErrorDetail',
  tryAgain: 'VtaLinkTryAgain',
  scanAgain: 'VtaLinkScanAgain',
  byAddress: 'VtaLinkByAddress',
} as const
export type VtaLinkId = (typeof VtaLinkIds)[keyof typeof VtaLinkIds]
