name: Update Release PR or Publish
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/main.yaml'
      - '.github/workflows/publish.yaml'
      - '.github/actions/setup-node/action.yaml'
      - 'packages/**'
      - 'package.json'
      - 'yarn.lock'
      - '.changeset/**'

permissions:
  pull-requests: write
  contents: write
  id-token: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout bifold-wallet
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.11'

      - name: Setup NodeJS
        uses: ./.github/actions/setup-node

      - name: Install dependencies
        run: |
          yarn install --immutable

      - name: Upgrade npm for Trusted Publishers support
        run: |
          npm install -g npm@^11

      - name: Update release PR or publish to npm
        id: changesets
        uses: changesets/action@a45c4d594aa4e2c509dc14a9f2b3b67ba3780d0d # v1.9.0
        with:
          title: 'chore(release): new version'
          commit: 'chore(release): new version'
          publish: yarn release
          version: yarn changeset-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true

      - name: Get current package version
        id: get_version
        run: echo "version=$(node -p "require('./packages/core/package.json').version")" >> $GITHUB_OUTPUT

      - name: Create GitHub release
        if: "startsWith(github.event.head_commit.message, 'chore(release): new version')"
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
