/**
 * GENERATED by scripts/bundle-vetting-schemas.mjs — do not edit by hand. The
 * published JSON Schemas Keyring checks vetting documents against, bundled
 * self-contained from trust-tasks-tf at bdae1cf9:
 *
 * - `vettingSessionPayload` — vetting/session/0.1 payload.schema.json
 * - `vettingCard` — vetting/_shared/0.1/vetting-card.schema.json#/$defs/VettingCard
 *   (what vta-sdk `vetting::card::parse_card` validates, card.rs:203-207)
 * - `vettingRequirements` — vtc/join-requests/manifest/0.2 #/$defs/VettingRequirements
 *   (vta-sdk `protocols::vetting::read_requirements`, vetting.rs:485)
 * - `vetterProfilePayload` — vtc/vetting/vetters/profile/0.1 payload.schema.json
 *
 * These are the schemas vta-sdk validates against (`against_own_schema`,
 * `against_definition`, protocols/vetting.rs:406-431). What JSON Schema
 * cannot say is in vettingShape.ts.
 *
 * @module trust-tasks/module/vettingSchemas
 */

/* eslint-disable */
export const VETTING_SCHEMAS: Record<
  'vettingSessionPayload' | 'vettingCard' | 'vettingRequirements' | 'vetterProfilePayload',
  Record<string, unknown>
> = {
  vettingSessionPayload: {
    type: 'object',
    additionalProperties: false,
    required: ['requestId', 'challenge', 'domain', 'method', 'requiredClaims', 'expiresAt'],
    properties: {
      requestId: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
      },
      challenge: {
        type: 'string',
        pattern: '^[A-Za-z0-9_-]{43}$',
      },
      domain: {
        type: 'string',
        pattern: '^did:',
      },
      method: {
        $ref: '#/$defs/VettingMethod',
      },
      requiredClaims: {
        type: 'array',
        uniqueItems: true,
        items: {
          $ref: '#/$defs/ClaimType',
          not: {
            const: 'person.portrait',
          },
        },
      },
      optionalClaims: {
        type: 'array',
        uniqueItems: true,
        items: {
          $ref: '#/$defs/ClaimType',
          not: {
            const: 'person.portrait',
          },
        },
      },
      expiresAt: {
        type: 'string',
        format: 'date-time',
      },
      ext: {
        $ref: '#/$defs/Ext',
      },
    },
    $defs: {
      VettingMethod: {
        type: 'string',
        enum: ['inPerson', 'video', 'priorAcquaintance'],
      },
      ClaimType: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^(x:)?[a-z][a-zA-Z0-9]*(\\.[a-z][a-zA-Z0-9]*)*$',
      },
      Ext: {
        type: 'object',
        minProperties: 1,
        additionalProperties: true,
        propertyNames: {
          pattern: '^[a-z][a-z0-9-]*(\\.[a-z0-9-]+)+$',
        },
      },
    },
  },
  vettingCard: {
    type: 'object',
    additionalProperties: false,
    required: [
      'type',
      'id',
      'publisher',
      'cardVersion',
      'audience',
      'community',
      'challenge',
      'domain',
      'issuedAt',
      'expiresAt',
      'claims',
      'identityCommitment',
      'commitmentSalt',
      'proof',
    ],
    properties: {
      type: {
        type: 'array',
        minItems: 3,
        maxItems: 3,
        uniqueItems: true,
        items: {
          type: 'string',
          enum: ['VerifiableDataStructure', 'RelationshipCard', 'VettingCard'],
        },
      },
      id: {
        type: 'string',
        pattern: '^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
      },
      publisher: {
        type: 'string',
        pattern: '^did:',
      },
      cardVersion: {
        type: 'integer',
        minimum: 1,
      },
      audience: {
        type: 'string',
        pattern: '^did:',
      },
      community: {
        type: 'string',
        pattern: '^did:',
      },
      challenge: {
        type: 'string',
        pattern: '^[A-Za-z0-9_-]{43}$',
      },
      domain: {
        type: 'string',
        pattern: '^did:',
      },
      issuedAt: {
        type: 'string',
        format: 'date-time',
      },
      expiresAt: {
        type: 'string',
        format: 'date-time',
      },
      claims: {
        type: 'array',
        minItems: 1,
        items: {
          $ref: '#/$defs/VettingCardClaim',
        },
      },
      identityCommitment: {
        $ref: '#/$defs/DigestMultibase',
      },
      commitmentSalt: {
        type: 'string',
        pattern: '^[A-Za-z0-9_-]{43}$',
      },
      proof: {
        $ref: '#/$defs/DataIntegrityProof',
      },
    },
    $defs: {
      ClaimType: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^(x:)?[a-z][a-zA-Z0-9]*(\\.[a-z][a-zA-Z0-9]*)*$',
      },
      VettingCardClaim: {
        type: 'object',
        additionalProperties: false,
        required: ['type', 'value', 'provenance'],
        properties: {
          type: {
            $ref: '#/$defs/ClaimType',
            not: {
              const: 'person.portrait',
            },
          },
          value: {},
          provenance: {
            type: 'string',
            minLength: 1,
            maxLength: 64,
            pattern: '^[a-z][a-zA-Z0-9]*$',
          },
        },
      },
      DigestMultibase: {
        type: 'string',
        minLength: 16,
        pattern: '^(z[1-9A-HJ-NP-Za-km-z]+|u[A-Za-z0-9_-]+)$',
      },
      DataIntegrityProof: {
        type: 'object',
        additionalProperties: true,
        required: ['type', 'cryptosuite', 'verificationMethod', 'proofPurpose', 'proofValue'],
        properties: {
          type: {
            type: 'string',
            const: 'DataIntegrityProof',
          },
          cryptosuite: {
            type: 'string',
            minLength: 1,
            maxLength: 64,
            pattern: '^[a-z0-9-]+$',
          },
          verificationMethod: {
            type: 'string',
            pattern: '^did:',
          },
          proofPurpose: {
            type: 'string',
            const: 'assertionMethod',
          },
          proofValue: {
            type: 'string',
            pattern: '^z[1-9A-HJ-NP-Za-km-z]+$',
          },
        },
      },
    },
  },
  vettingRequirements: {
    type: 'object',
    additionalProperties: true,
    required: ['version', 'statementType', 'minStatements', 'acceptedMethods', 'eligibleVetters'],
    properties: {
      version: {
        type: 'string',
        pattern: '^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$',
      },
      statementType: {
        type: 'string',
        format: 'uri',
        minLength: 1,
        maxLength: 512,
      },
      minStatements: {
        type: 'integer',
        minimum: 1,
      },
      minByMethod: {
        type: 'object',
        propertyNames: {
          $ref: '#/$defs/VettingMethod',
        },
        additionalProperties: {
          type: 'integer',
          minimum: 0,
        },
      },
      acceptedMethods: {
        type: 'array',
        minItems: 1,
        uniqueItems: true,
        items: {
          $ref: '#/$defs/VettingMethod',
        },
      },
      acceptedDocumentClasses: {
        type: 'array',
        minItems: 1,
        uniqueItems: true,
        items: {
          $ref: '#/$defs/VettingDocumentation',
        },
      },
      requiredClaims: {
        type: 'array',
        uniqueItems: true,
        items: {
          $ref: '#/$defs/ClaimType',
        },
      },
      optionalClaims: {
        type: 'array',
        uniqueItems: true,
        items: {
          $ref: '#/$defs/ClaimType',
        },
      },
      maxStatementAge: {
        $ref: '#/$defs/Duration',
      },
      eligibleVetters: {
        type: 'object',
        additionalProperties: false,
        required: ['role'],
        properties: {
          role: {
            type: 'string',
            minLength: 1,
            maxLength: 128,
            pattern: '^[a-zA-Z][a-zA-Z0-9_-]*$',
          },
        },
      },
      independence: {
        type: 'object',
        additionalProperties: false,
        properties: {
          maxByDeclaredRelationship: {
            type: 'object',
            propertyNames: {
              $ref: '#/$defs/VettingRelationship',
            },
            additionalProperties: {
              type: 'integer',
              minimum: 0,
            },
          },
          requireConsistentIdentityCommitment: {
            type: 'boolean',
          },
        },
      },
      invitation: {
        type: 'string',
        enum: ['required', 'optional', 'none'],
      },
      decisionSla: {
        $ref: '#/$defs/Duration',
      },
      requirementsGrace: {
        $ref: '#/$defs/Duration',
      },
      governanceFrameworkUrl: {
        type: 'string',
        format: 'uri',
        pattern: '^https://',
        maxLength: 2048,
      },
    },
    $defs: {
      VettingMethod: {
        type: 'string',
        enum: ['inPerson', 'video', 'priorAcquaintance'],
      },
      VettingDocumentation: {
        type: 'string',
        minLength: 1,
        maxLength: 64,
        pattern: '^[a-z][a-zA-Z0-9]*$',
      },
      ClaimType: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^(x:)?[a-z][a-zA-Z0-9]*(\\.[a-z][a-zA-Z0-9]*)*$',
      },
      Duration: {
        type: 'string',
        maxLength: 32,
        pattern:
          '^P(([0-9]+W)?([0-9]+D)?T([0-9]+H([0-9]+M)?([0-9]+S)?|[0-9]+M([0-9]+S)?|[0-9]+S)|[0-9]+W([0-9]+D)?|[0-9]+D)$',
      },
      VettingRelationship: {
        type: 'string',
        enum: ['none', 'communityColleague', 'sameEmployer', 'family', 'otherPersonal'],
      },
    },
  },
  vetterProfilePayload: {
    type: 'object',
    additionalProperties: false,
    required: ['listed', 'languages', 'methods', 'acceptsDocumentation', 'events'],
    properties: {
      listed: {
        type: 'boolean',
      },
      displayName: {
        $ref: '#/$defs/VetterDisplayName',
      },
      languages: {
        type: 'array',
        maxItems: 16,
        uniqueItems: true,
        items: {
          $ref: '#/$defs/LanguageTag',
        },
      },
      location: {
        $ref: '#/$defs/VetterLocation',
      },
      methods: {
        $ref: '#/$defs/VetterMethods',
      },
      acceptsDocumentation: {
        $ref: '#/$defs/VetterAcceptsDocumentation',
      },
      availability: {
        $ref: '#/$defs/VetterAvailability',
      },
      contactHint: {
        $ref: '#/$defs/VetterContactHint',
      },
      events: {
        type: 'array',
        maxItems: 32,
        items: {
          $ref: '#/$defs/VetterEvent',
        },
      },
      ext: {
        $ref: '#/$defs/Ext',
      },
    },
    $defs: {
      VetterDisplayName: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
      },
      LanguageTag: {
        type: 'string',
        minLength: 2,
        maxLength: 35,
        pattern: '^[A-Za-z]{2,3}(-[A-Za-z0-9]{1,8})*$',
      },
      CountryCode: {
        type: 'string',
        pattern: '^[A-Z]{2}$',
      },
      PlaceName: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
      },
      VetterLocation: {
        type: 'object',
        additionalProperties: false,
        required: ['country'],
        properties: {
          country: {
            $ref: '#/$defs/CountryCode',
          },
          region: {
            $ref: '#/$defs/PlaceName',
          },
          city: {
            $ref: '#/$defs/PlaceName',
          },
        },
      },
      VettingMethod: {
        type: 'string',
        enum: ['inPerson', 'video', 'priorAcquaintance'],
      },
      VetterMethods: {
        type: 'array',
        minItems: 1,
        maxItems: 3,
        uniqueItems: true,
        items: {
          $ref: '#/$defs/VettingMethod',
        },
      },
      VettingDocumentation: {
        type: 'string',
        minLength: 1,
        maxLength: 64,
        pattern: '^[a-z][a-zA-Z0-9]*$',
      },
      VetterAcceptsDocumentation: {
        type: 'array',
        maxItems: 16,
        uniqueItems: true,
        items: {
          $ref: '#/$defs/VettingDocumentation',
        },
      },
      VetterAvailability: {
        type: 'string',
        minLength: 1,
        maxLength: 500,
      },
      VetterContactHint: {
        type: 'string',
        minLength: 1,
        maxLength: 300,
      },
      CalendarDate: {
        type: 'string',
        format: 'date',
        pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}$',
      },
      VetterEvent: {
        type: 'object',
        additionalProperties: false,
        required: ['name', 'startDate', 'endDate'],
        properties: {
          name: {
            type: 'string',
            minLength: 1,
            maxLength: 200,
          },
          startDate: {
            $ref: '#/$defs/CalendarDate',
          },
          endDate: {
            $ref: '#/$defs/CalendarDate',
          },
          location: {
            $ref: '#/$defs/VetterLocation',
          },
          url: {
            type: 'string',
            format: 'uri',
            pattern: '^https://',
            maxLength: 2048,
          },
        },
      },
      Ext: {
        type: 'object',
        minProperties: 1,
        additionalProperties: true,
        propertyNames: {
          pattern: '^[a-z][a-z0-9-]*(\\.[a-z0-9-]+)+$',
        },
      },
    },
  },
}
